---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/vpc_setup.txt

    - name: Import VPC setup Variables
      include_vars: vars/output_vars

    - name: Create ec2 key
      ec2_key:
        name: bastion-key
        region: "{{ region }}"
      register: keyout


    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: "/home/ubuntu/ansible-aws-vpc/bastion-key.pem"
        mode: 0400
      when: keyout.changed
    
    - name: Create Sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port withinsg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ MYIP }}"
      register: BastionSG_out
      
    - name: Check if Bastion host already exists
      ec2_instance_info:
        filters:
          "tag:Name": "vprofile"
          "tag:Project": "vprofile"
          "tag:Owner": "AlexDevOps"
        region: "{{ region }}"
      register: bastion_instance_info

    - name: Debug output of ec2_instance_info
      debug:
        var: bastion_instance_info.instances

    - name: Create Bastion host
      ec2_instance:
        key_name: bastion-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        subnet_id: "{{ pubsub1id }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: vprofile
          Project: vprofile
          Owner: AlexDevOps
        security_group: "{{ BastionSG_out.group_id }}"
      register: bastionHost_out
      when: bastion_instance_info.instances | selectattr('state.name', 'not in', ['terminated', 'pending']) | list | length == 0
      

    