---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/bastion_setup.txt

    - name: Import VPC setup Variables
      include_vars: vars/output_vars

    - name: Create ec2 key
      ec2_key:
        name: bastion-key
        region: "{{ region }}"
      register: keyout


    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: " ./bastion-key.pem"
        mode: 0600
      when: keyout.changed
    
    - name: Create Sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port withinsg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - name: Create Bastion host
      ec2_instance:
        key_name: "{{ keyout }}"
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: vprofile
          Project: vprofile
          Owner: AlexDevOps
        security_group: "{{ BastionSG_out.group_id }}"
      register: bastionHost_out
      when: bastion_instance_info.instances | length == 0