- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCird}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:                
        msg:
         - "Region: {{ region }}"
         - "Zone1: {{ zone1 }}"
         - "State: {{ state }}"
         - "VPC ID: {{ vpcout }}"
         - "CIDR: {{ PubSub1Cidr }}"

    - name: Create Public Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: yes
        tags:
          Name: PubSub1
      register: pubsub1_out

       