---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/output_vars
    
    - name: Import VPC setup Variables
      include_vars: vars/vpc_setup.txt

    - name: Import vprostacksetup variables
      include_vars: vars/vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out


    - name: Save private key into file vprokey.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "/home/ubuntu/ansible-aws-vpc/vpro-key.pem"
        mode: 0400
      when: vprokey_out.changed