---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/output_vars
    
    - name: Import VPC setup Variables
      include_vars: vars/vpc_setup.txt

    - name: Import vprostacksetup variables
      include_vars: vars/vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out


    - name: Save private key into file vprokey.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "/home/ubuntu/ansible-aws-vpc/vpro-key.pem"
        mode: 0400
      when: vprokey_out.changed

    - name: Create security_group for Load Balancer
      ec2_group:
        name: load-balancer-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: "{{ 0.0.0.0/0 }}"
      register: LB_out

    - name: Create security_group for Load Balancer
      ec2_group:
        name: vprostack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          group_id: "{{ LB_out }}"
        - proto: tcp
          from_port: 22
          to_port: 22
          group_id: "{{ BastionSGid }}"
      register: LB_out